---
### harbor imagePullSecret
apiVersion: v1
data:
  .dockerconfigjson:  eyJhdXRocyI6eyJodWIuYy4xNjMuY29tL3Fpbmd6aG91Ijp7InVzZXJuYW1lIjoic3RhZmYucWluZ3pob3VAc2VydmljZS5uZXRlYXNlLmNvbSIsInBhc3N3b3JkIjoiUWluZ3pob3U0MzIxIiwiZW1haWwiOiJzdGFmZi5xaW5nemhvdUBzZXJ2aWNlLm5ldGVhc2UuY29tIiwiYXV0aCI6ImMzUmhabVl1Y1dsdVozcG9iM1ZBYzJWeWRtbGpaUzV1WlhSbFlYTmxMbU52YlRwUmFXNW5lbWh2ZFRRek1qRT0ifX19
kind: Secret
metadata:
  name: qingzhou-secret
  namespace: istio-system
type: kubernetes.io/dockerconfigjson
