---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qz-egress
  namespace: istio-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: qz-egress
  namespace: istio-system
data:
  proxy.conf: |-
    server {
       listen 80;
        location / {
           proxy_set_header Host $host;
           proxy_set_header Zw-Test asdf;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header xxxxx $proxy_add_x_forwarded_for;
           proxy_pass http://10.177.1.3:8090;
       }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qz-egress
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qz-egress
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: qz-egress
    spec:
      serviceAccountName: qz-egress
      containers:
      - name: nginx
        image: nginx:1.17
        imagePullPolicy: Always
        volumeMounts:
        - name: qz-egress-conf
          mountPath: /etc/nginx/conf.d
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 500m
      volumes:
      - name: qz-egress-conf
        configMap:
          name: qz-egress
      imagePullSecrets:
      - name: "qingzhou-secret"
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: qz-egress
  namespace: istio-system
spec:
  targets:
  - name: qz-egress
  peers:
  - mtls: {}
---
apiVersion: v1
kind: Service
metadata:
  name: qz-egress
  namespace: istio-system
  labels:
    app: qz-egress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: qz-egress
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: qz-egress
  namespace: istio-system
spec:
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  host: qz-egress
